apiVersion: apps/v1
kind: Deployment
metadata:
  name: debugging
  namespace: training
  labels:
    app: debugging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debugging
  template:
    metadata:
      labels:
        app: debugging
    spec:
      containers:
      - name: web-app
        image: nginx_i_do_not_exist:777
        ports:
        - containerPort: 9090