apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-first-deployment
  namespace: training
  labels:
    app: nginx-deployment
spec:
  replicas: 4
  strategy: #Enable rolling update
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: my-first-pod-label
  template:
    metadata:
      labels:
        app: my-first-pod-label
    spec:
      containers:
      - name: nginx
        image: nginx:3.7.9