apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-first-deployment
  namespace: training
  labels:
    app: nginx-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: my-first-pod-label
  template:
    metadata:
      labels:
        app: my-first-pod-label
    spec:
      containers:
      - name: my-first-container
        image: nginx