apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim
spec:
  storageClassName: slow  ## must match with PV
  accessModes:
    - ReadWriteMany  ## must match with PV
  resources:
    requests:
      storage: 10Gi  ## must be less or equal with PV
