apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
spec:
  capacity:
    storage: 5Gi  ## Size
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany ## ReadWriteOnce, ReadOnlyMany, ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle ##Retain, Recycle, Delete
  storageClassName: slow ## Just for devops organization
  hostPath:
    path: "/mnt/data"