apiVersion: v1
kind: Service
metadata:
  name: web-app-service
  namespace: default
  labels:
    service: web-app-service
spec:
  ports:
  - port: 9090
    protocol: TCP
  selector:
    app: web-app-backend