apiVersion: v1
kind: Pod
metadata:
  name: volumes-pod
  namespace: k8s-training
spec:
  containers:
  - image: busybox
    name: busybox-container
    command:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 3000;
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 2
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}